### ISSUE TITLE
Doesn't work on mobile (Firefox for Android)

### ISSUE THREAD

**Issue by blablablerg** [SeinopSys/YTMySubs#1]
This plugin is a godsend! It helps me with all the clickbait on youtube, which was making go crazy Thanks a lot. 

Unfortunately, it doesn't work on Firefox for Android (yet, i hope), mayb it has something to do with the URL? (m.youtube.com). 

If you could fix that, we could also safely browse youtube on Android mobiles :)

Thx!

**Comment by SeinopSys** [comment]
I published version 1.0.3 which has a check for `m.youtube.com` as well.

**Comment by SeinopSys** [comment]
@blablablerg Has the updated version worked for you?

**Comment by SeinopSys** [comment]
I've published v1.0.4 which I confirmed to work on Desktop Chrome using the responsive testing tools, so I'm hoping this solves this issue for Firefox as well. My previous fix was missing a crucial option, but this will take care of it now. If you find that it's not fixed feel free to respond and I'll investigate further.
