### ISSUE TITLE
Feature request: add an option to still go to 'Home' when clicking on 'Home' in the sidebar

### ISSUE THREAD

**Issue by zjeffer** [SeinopSys/YTMySubs#2]
I love this addon, but sometimes I might want to go to the actual homescreen instead of my subscriptions.

**Comment by SeinopSys** [comment]
You'll have to disable the extension if you do. The extension's main goal is to avoid the home page at all cost.

**Comment by zjeffer** [comment]
How about an option in the toolbar to quickly disable and enable the addon?

**Comment by SeinopSys** [comment]
I have no intention of making this extension any more complex by adding customization options.
