### ISSUE TITLE
Compactify the subs

### ISSUE THREAD

**Issue by DonaldTsang** [SeinopSys/YTMySubs#3]
Make it such that the Subs look like the recommendations in regards to layout.
The last space it wastes, the more we can see.

**Comment by SeinopSys** [comment]
That's way beyond the scope of this extension.

**Comment by DonaldTsang** [comment]
I think it has been done by someone else but not necessarily good. For reference
- https://github.com/OsaSoft/youtube-better-subscriptions
- https://addons.mozilla.org/en-US/firefox/addon/youtube-better-subscriptions
