### ISSUE TITLE
Sidebar/Masthead logo now redirects to the home page

### ISSUE THREAD

**Issue by xcasxcursex** [SeinopSys/YTMySubs#5]
Looks like youtube changed something, although it's possible it was firefox, I'm using nightly. I wonder if you're able to get around this new behaviour?

I've been rather enjoying never seeing the home page, so thanks :)

**Comment by SeinopSys** [comment]
First off, you really should not be daily driving nightly, and it's definitely not my aim to support pre-release browser versions.

That said I did just download it and the extension did what it was supposed to. My best guess is that you are stuck with some form of A/B test from YouTube themselves which I'm not seeing on my end. Without reproduction steps I'm unfortunately unable to resolve your issue.

**Comment by xcasxcursex** [comment]
I have to daily drive nightly. I needed a fix which was not coming to beta for some months so nightly was a necessity. The intention here is not to support the pre-release version but to be aware that it is a change coming to future stable releases.

Reproduction steps are simple. 
Open www.youtube.com from the URL bar or other link. You will be redirected to the subscriptions page as expected.
Click the Youtube logo at the top left of the page (masthead/'sidebar'). You will be directed to the home page.

If you can't reproduce this then yep, I'm probably on some kind of A/B test and there's nothing you can do. At least you will be aware of it, if they roll this out to everybody. Hopefully they will roll it back and I won't have to put up with it any more. Sucks to be me!

**Comment by SeinopSys** [comment]
That's exactly how I tried to do it when checking yesterday, and it worked on my end. Sorry but I can't really help you until I get it to happen on my end as well. Rest assured I use YouTube daily and will definitely notice if/when this breaks. Thank you for bringing it to my attention.

**Comment by xcasxcursex** [comment]
Thanks mate :)

**Comment by SeinopSys** [comment]
Jolly good news, I have been hit with the same behavior at last and absolutely hate it all the same, time to get this sorted

**Comment by SeinopSys** [comment]
I just released v1.0.5 on both Chrome Web Store and Mozilla Add-ons, whenever the update passes verification in the respective extension stores the fix will be applied once the extension/add-on is updated by your browser.

**Comment by xcasxcursex** [comment]
Thanks heaps mate!
