### ISSUE TITLE
Question: Why redirect explicit "home" link? (And not hide it)

### ISSUE THREAD

**Issue by JasonJAyalaP** [SeinopSys/YTMySubs#6]
I use the extension because subscriptions is a better home for youtube, but I explicitly want to view YTs sometimes useful often not suggestion page (home), I don't have that option without disabling the extension. In this situation, the "home" link is more than redundant. It could be at least hidden.

But I see that the "home" link is simply youtube.com. There isn't a "youtube.com/home" for the Home link to redirected to.

**Comment by SeinopSys** [comment]
Redirecting the root is the simplest way to achieve what I need from this extension, which is to never be able to see the home page. The goal is to replace the page, not to have it be replaced sometimes but not others, and I definitely do not want to get into the complexity of manipulating things on the page. Your best bet is to disable the extension if you need to visit that page.
